apiVersion: apps/v1
kind: Deployment
metadata:
  name: addresss-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addresss
  template:
    metadata:
      labels:
        app: addresss
    spec:
      containers:
        - name: addresss
          image: {image......}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password  
          ports: 
            - containerPort: 5000     
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: addresss
  ports:
    - name: addresss
      protocol: TCP
      port: 5000
      targetPort: 3000
